### ISSUE TITLE
Erro EXPO

### ISSUE THREAD

**Issue by rcouto79** [RafaelAlthaus/react-native-juno#1]
Em CLI funcionou perfeito.
Porém no EXPO não funciona tanto Android quanto iOS. Apresenta o seguinte erro:

TypeError: _reactNativeJuno.default.initialize is not function.

![erro_juno](https://user-images.githubusercontent.com/11380336/94735469-31e85780-0341-11eb-8ed0-e9d1fdd469bc.jpg)

**Comment by RafaelAlthaus** [comment]
Rodrigo, infelizmente o Expo é limitado nesse sentido e não possuí suporte para módulos nativos. Para remediar esse problema, sugiro ejetar para o ExpoKit: https://docs.expo.io/expokit/eject/

**Comment by rcouto79** [comment]
Obrigado!
